### ISSUE TITLE
Poynting correction is adding 'None' to the interaction string

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/PyCMDS#125]
This causes the Processing to fail, after already creating the curve file

Actual exception in wt.tuning.workup, but I suspect PyCMDS is to blame

```
ACQUISITION ERROR: unhashable type: 'list'
Traceback (most recent call last):
  File "C:\Users\John\Desktop\PyCMDS\somatic\queue.py", line 203, in execute_acq
uisition
    worker.run()
  File "C:\Users\John\Desktop\PyCMDS\somatic\modules\poynting_tune.py", line 116
, in run
    wt.tuning.workup.intensity(data, curve, channel, save_directory = scan_folde
r)
  File "C:\Users\John\Documents\MyScripts\WrightTools\tuning\workup.py", line 15
3, in intensity
    curve.save(save_directory=save_directory, full=True)
  File "C:\Users\John\Documents\MyScripts\WrightTools\tuning\curve.py", line 600
, in save
    self.plot(autosave=True, save_path=image_path, title=title)
  File "C:\Users\John\Documents\MyScripts\WrightTools\tuning\curve.py", line 499
, in plot
    lowest_ax_dictionary[curve.interaction] =axs[ax_index]
TypeError: unhashable type: 'list'
```

**Comment by ksunden** [comment]
I believe this has long been fixed
