### ISSUE TITLE
Constants do not allow delay variables

### ISSUE THREAD

**Issue by ksunden** [wright-group/PyCMDS#155]
You can select them from the drop down, but if you refer to them in the expression, you get a key error.

```
ACQUISITION ERROR: 'd1'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/numexpr/necompiler.py", line 736, in getArguments
    a = local_dict[name]
KeyError: 'd1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyle/wright/PyCMDS/somatic/queue.py", line 203, in execute_acquisition
    worker.run()
  File "/home/kyle/wright/PyCMDS/somatic/modules/scan.py", line 182, in run
    self.scan(axes, constants)
  File "/home/kyle/wright/PyCMDS/somatic/acquisition.py", line 243, in scan
    arr[idx] = numexpr.evaluate(expression, vals)
  File "/usr/lib64/python3.6/site-packages/numexpr/necompiler.py", line 803, in evaluate
    arguments = getArguments(names, local_dict, global_dict)
  File "/usr/lib64/python3.6/site-packages/numexpr/necompiler.py", line 738, in getArguments
    a = global_dict[name]
KeyError: 'd1'
```

**Comment by ksunden** [comment]
Line 176 of modules/scan.py sets the units to 'wn' regardless of the actual units with the comment `#TODO: this is a hack, remove it`

**Comment by ksunden** [comment]
https://github.com/wright-group/PyCMDS/blob/a27b0b17606dd7276e1b74510e89383bee47194d/somatic/modules/scan.py#L176
