### ISSUE TITLE
Division by zero error on startup

### ISSUE THREAD

**Issue by ksunden** [wright-group/PyCMDS#97]
Following error during startup:
```
Traceback (most recent call last):
  File "C:\Users\John\Desktop\PyCMDS\hardware\hardware.py", line 158, in on_offset_updated
    new = self.hardware.offset.read(self.hardware.native_units)
  File "C:\Users\John\Desktop\PyCMDS\project\classes.py", line 535, in read
    value = wt_units.converter(value, self.units, output_units)
  File "C:\Users\John\Documents\MyScripts\WrightTools\units.py", line 83, in converter
    native = eval(dic[current_unit][0])
  File "<string>", line 1, in <module>
ZeroDivisionError: float division by zero
```

**Comment by ksunden** [comment]
Added try/except in WrightTools.units.converter() on the conversion to native units. If ZeroDivisionError occurs, sets the native to np.inf and continues

Such a try/except was already present in the conversion from native to requested
